name: tinode
description: This SDK implements Tinode client-side protocol for multi platform applications based on dart.
version: 1.0.0
homepage: https://tinode.co/

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  rxdart: ^0.27.7
  web_socket_channel: ^2.4.0
  get_it: ^7.6.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.3